// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvlsqbccnancbzgeohwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bHNxYmNjbmFuY2J6Z2VvaHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTUyODcsImV4cCI6MjA2ODQ5MTI4N30.43wt4B2vgrGQbGuw-qfsEcXyijHJDlDGp3Y5kb-bchQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
